from django.contrib import admin
from veoc.models import *

# Register your models here.

admin.site.register(call_incident_category)
admin.site.register(persons)
admin.site.register(incident_status)
admin.site.register(unrelated_calls_category)
admin.site.register(call_log)
admin.site.register(user_profile)
admin.site.register(contact)
admin.site.register(contact_type)
admin.site.register(county)
admin.site.register(data_source)
admin.site.register(designation)
admin.site.register(event_type)
admin.site.register(disease_type)
admin.site.register(sub_county)
admin.site.register(reporting_region)
admin.site.register(event)
admin.site.register(disease)
admin.site.register(facilities)
admin.site.register(police_post)
admin.site.register(referral_labs)
admin.site.register(watcher_team_leads)
admin.site.register(watcher_teams)
admin.site.register(watchers_shifts)
admin.site.register(eoc_events_calendar)
admin.site.register(eoc_status)
admin.site.register(repository_categories)
admin.site.register(document_repository)
admin.site.register(organizational_units)
admin.site.register(staff_contact)
admin.site.register(watcher_schedule)
admin.site.register(system_modules)
admin.site.register(feedback)
