# Generated by Django 2.0 on 2019-03-14 15:41

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,12}$')])),
                ('email_address', models.EmailField(blank=True, max_length=20)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('contact_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='veoc.contact_type')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.county')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_updated_by', to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='veoc.designation')),
                ('subcounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.sub_county')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_status', models.CharField(default='Rumour', max_length=20)),
                ('date_reported', models.DateTimeField(default=datetime.datetime.now)),
                ('cases', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('remarks', models.TextField(max_length=500)),
                ('action_taken', models.TextField(default='None', max_length=500)),
                ('significant', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.county')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='eoc_events_calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_updated_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='eoc_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_description', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_status', models.CharField(default='Rumour', max_length=20)),
                ('date_reported', models.DateTimeField(default=datetime.datetime.now)),
                ('cases', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('remarks', models.TextField(max_length=500)),
                ('significant_event', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.county')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100)),
                ('facility_level', models.CharField(max_length=10)),
                ('facility_type', models.CharField(default='Private', max_length=10)),
                ('mfl_code', models.CharField(max_length=10)),
                ('latitude', models.CharField(default='0.0000', max_length=100)),
                ('longitude', models.CharField(default='0.0000', max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.county')),
                ('subcounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.sub_county')),
            ],
        ),
        migrations.CreateModel(
            name='police_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_post_code', models.CharField(max_length=50)),
                ('police_post_name', models.CharField(max_length=50)),
                ('ocs_names', models.CharField(max_length=50)),
                ('ocs_phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,12}$')])),
                ('latitude', models.CharField(default='0.0000', max_length=100)),
                ('longitude', models.CharField(default='0.0000', max_length=100)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.county')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_updated_by', to=settings.AUTH_USER_MODEL)),
                ('subcounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.sub_county')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='referral_labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_referral_code', models.CharField(max_length=10)),
                ('lab_referral_name', models.CharField(max_length=20)),
                ('lead_lab_tech_name', models.CharField(max_length=20)),
                ('lead_lab_tech_phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,12}$')])),
                ('latitude', models.CharField(default='0.0000', max_length=100)),
                ('longitude', models.CharField(default='0.0000', max_length=100)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.county')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refferal_updated_by', to=settings.AUTH_USER_MODEL)),
                ('subcounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.sub_county')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refferal_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='repository_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='repository_publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=50)),
                ('myfile', models.FileField(upload_to='repository_publications')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='watcher_team_leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_updated_by', to=settings.AUTH_USER_MODEL)),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.contact')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='watcher_teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher_team_updated_by', to=settings.AUTH_USER_MODEL)),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.watcher_team_leads')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.contact')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher_team_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='watchers_shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField(default=0)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher_shift_updated_by', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.watcher_team_leads')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher_shift_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='call_log',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='call_log',
            name='reporting_region',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='veoc.reporting_region'),
        ),
        migrations.AlterField(
            model_name='call_log',
            name='county',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='veoc.county'),
        ),
        migrations.AlterField(
            model_name='call_log',
            name='subcounty',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='veoc.sub_county'),
        ),
        migrations.AlterField(
            model_name='data_source',
            name='source_description',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.data_source'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.event_type'),
        ),
        migrations.AddField(
            model_name='event',
            name='reporting_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.reporting_region'),
        ),
        migrations.AddField(
            model_name='event',
            name='subcounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.sub_county'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disease',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.data_source'),
        ),
        migrations.AddField(
            model_name='disease',
            name='disease_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.disease_type'),
        ),
        migrations.AddField(
            model_name='disease',
            name='reporting_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.reporting_region'),
        ),
        migrations.AddField(
            model_name='disease',
            name='subcounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.sub_county'),
        ),
        migrations.AddField(
            model_name='disease',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
