# Generated by Django 2.0 on 2019-04-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0004_unrelated_calls_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease_type',
            name='call_incident_category',
        ),
        migrations.RemoveField(
            model_name='event_type',
            name='call_incident_category',
        ),
    ]
