# Generated by Django 2.0 on 2019-04-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0005_auto_20190415_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call_log',
            name='follow_up',
        ),
        migrations.AddField(
            model_name='call_log',
            name='call_category_incident',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unrelated_calls_category',
            name='call_incident_category_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='veoc.call_incident_category'),
        ),
    ]
