# Generated by Django 2.0 on 2019-05-29 06:16

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veoc', '0008_auto_20190429_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='organizational_units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('organisationunitid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('parentid', models.CharField(max_length=50)),
                ('hierarchylevel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='staff_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,12}$')])),
                ('email_address', models.EmailField(blank=True, max_length=20)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_staff_updated_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_staff_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
