# Generated by Django 2.0 on 2019-05-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0009_organizational_units_staff_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizational_units',
            name='latitude',
            field=models.CharField(default='0.0000', max_length=100),
        ),
        migrations.AddField(
            model_name='organizational_units',
            name='longitude',
            field=models.CharField(default='0.0000', max_length=100),
        ),
    ]
