# Generated by Django 2.0 on 2019-05-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0010_auto_20190530_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='idsr_weekly_reportable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
