# Generated by Django 2.0 on 2019-05-30 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0011_idsr_weekly_reportable'),
    ]

    operations = [
        migrations.CreateModel(
            name='dhis_disease_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dhis_event_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=1000)),
                ('longitude', models.CharField(default=36.8167, max_length=1000)),
                ('latitude', models.CharField(default=-1.2833, max_length=1000)),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.sub_county')),
            ],
        ),
    ]
