# Generated by Django 2.0 on 2019-05-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0012_dhis_disease_type_dhis_event_type_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='idsr_reported_incidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
