# Generated by Django 2.0 on 2019-05-30 18:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0013_idsr_reported_incidents'),
    ]

    operations = [
        migrations.CreateModel(
            name='dhis_disease_data_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='dhis_event_data_elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dhis_event_data_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_value', models.CharField(max_length=50)),
                ('data_element_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.dhis_event_data_elements')),
            ],
        ),
        migrations.CreateModel(
            name='dhis_reported_diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(default='Jt6SPO0bjKB', max_length=50)),
                ('eventDate', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='COMPLETED', max_length=50)),
                ('stored_by', models.CharField(default='eoc_user', max_length=10)),
                ('org_unit_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.organizational_units')),
            ],
        ),
        migrations.CreateModel(
            name='dhis_reported_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(default='hH7eq688OJT', max_length=50)),
                ('eventDate', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='COMPLETED', max_length=50)),
                ('stored_by', models.CharField(default='eoc_user', max_length=10)),
                ('org_unit_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.organizational_units')),
            ],
        ),
        migrations.CreateModel(
            name='idsr_diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='idsr_weekly_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idsr_disease_uid', models.CharField(max_length=50)),
                ('idsr_incident_uid', models.CharField(max_length=50)),
                ('org_unit_uid', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=100)),
                ('data_value', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='idsr_weekly_reportable',
            new_name='dhis_disease_data_elements',
        ),
        migrations.AddField(
            model_name='dhis_event_data_values',
            name='dhis_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.dhis_reported_events'),
        ),
        migrations.AddField(
            model_name='dhis_disease_data_values',
            name='data_element_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.dhis_disease_data_elements'),
        ),
        migrations.AddField(
            model_name='dhis_disease_data_values',
            name='dhis_disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.dhis_reported_diseases'),
        ),
    ]
