# Generated by Django 2.0 on 2019-06-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0015_auto_20190607_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='sub_county',
        ),
        migrations.AlterModelOptions(
            name='disease_type',
            options={'ordering': ('disease_description',)},
        ),
        migrations.AlterModelOptions(
            name='organizational_units',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='call_log',
            name='ward',
            field=models.ForeignKey(blank=True, default='2620', on_delete=django.db.models.deletion.CASCADE, related_name='call_log_ward', to='veoc.organizational_units'),
        ),
        migrations.AddField(
            model_name='disease',
            name='ward',
            field=models.ForeignKey(blank=True, default='2620', on_delete=django.db.models.deletion.CASCADE, related_name='disease_ward', to='veoc.organizational_units'),
        ),
        migrations.AddField(
            model_name='event',
            name='ward',
            field=models.ForeignKey(blank=True, default='2620', on_delete=django.db.models.deletion.CASCADE, related_name='event_ward', to='veoc.organizational_units'),
        ),
        migrations.AlterField(
            model_name='call_log',
            name='county',
            field=models.ForeignKey(blank=True, default='2620', on_delete=django.db.models.deletion.CASCADE, related_name='call_log_county', to='veoc.organizational_units'),
        ),
        migrations.AlterField(
            model_name='call_log',
            name='subcounty',
            field=models.ForeignKey(blank=True, default='2620', on_delete=django.db.models.deletion.CASCADE, related_name='call_log_subcounty', to='veoc.organizational_units'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='county',
            field=models.ForeignKey(blank=True, default='2620', on_delete=django.db.models.deletion.CASCADE, related_name='disease_county', to='veoc.organizational_units'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='subcounty',
            field=models.ForeignKey(blank=True, default='2620', on_delete=django.db.models.deletion.CASCADE, related_name='disease_subcounty', to='veoc.organizational_units'),
        ),
        migrations.AlterField(
            model_name='event',
            name='county',
            field=models.ForeignKey(blank=True, default='2620', on_delete=django.db.models.deletion.CASCADE, related_name='event_county', to='veoc.organizational_units'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subcounty',
            field=models.ForeignKey(blank=True, default='2620', on_delete=django.db.models.deletion.CASCADE, related_name='event_subcounty', to='veoc.organizational_units'),
        ),
        migrations.DeleteModel(
            name='ward',
        ),
    ]
