# Generated by Django 2.0 on 2019-06-18 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0016_auto_20190618_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_types', to='veoc.dhis_disease_type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_types', to='veoc.dhis_event_type'),
        ),
    ]
