# Generated by Django 2.0 on 2019-06-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0019_auto_20190620_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhis_disease_type',
            name='priority_disease',
            field=models.BooleanField(default=False),
        ),
    ]
