# Generated by Django 2.0 on 2019-07-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0020_dhis_disease_type_priority_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='action_taken',
        ),
        migrations.AlterField(
            model_name='disease',
            name='incident_status',
            field=models.CharField(default='Rumour', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='incident_status',
            field=models.CharField(default='Rumour', max_length=20),
        ),
    ]
