# Generated by Django 2.0 on 2019-07-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0021_auto_20190704_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='action_taken',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='disease',
            name='incident_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='veoc.incident_status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='incident_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='veoc.incident_status'),
        ),
    ]
