# Generated by Django 2.0 on 2019-07-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0022_auto_20190704_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhis_reported_diseases',
            name='period',
            field=models.CharField(default='000000', max_length=20),
        ),
        migrations.AddField(
            model_name='dhis_reported_events',
            name='period',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idsr_weekly_report',
            name='period',
            field=models.CharField(default='000000', max_length=100),
        ),
    ]
