# Generated by Django 2.0 on 2019-07-11 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0023_auto_20190711_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhis_reported_diseases',
            name='disease_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dhis2_disease_types', to='veoc.dhis_disease_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dhis_reported_events',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='veoc.dhis_event_type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dhis_reported_events',
            name='org_unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhis2_events_types', to='veoc.organizational_units'),
        ),
    ]
