# Generated by Django 2.0 on 2019-07-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0024_auto_20190711_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhis_disease_data_values',
            name='sent_status',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='dhis_event_data_values',
            name='sent_status',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
