# Generated by Django 2.0 on 2019-08-12 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veoc', '0027_auto_20190723_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='moh_linelisting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('patient_statud', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('subcounty', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('sublocation', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=20)),
                ('ward', models.CharField(max_length=20)),
                ('facility', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=20)),
                ('date_seen', models.DateField(max_length=20)),
                ('date_onset', models.CharField(max_length=20)),
                ('epi_week', models.CharField(max_length=20)),
                ('doses_of_vaccine', models.IntegerField(max_length=20)),
                ('lab_test', models.CharField(max_length=20)),
                ('speciment_taken', models.CharField(max_length=20)),
                ('speciment_date', models.IntegerField(max_length=20)),
                ('speciment_type', models.CharField(max_length=20)),
                ('lab_results', models.CharField(max_length=20)),
                ('rdt', models.CharField(max_length=20)),
                ('culture', models.CharField(max_length=20)),
                ('outcome', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=100)),
                ('next_of_kin', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_unit', models.ForeignKey(blank=True, default='2620', on_delete=django.db.models.deletion.CASCADE, related_name='persons_org_uit', to='veoc.organizational_units')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
