# Generated by Django 2.0 on 2019-08-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0028_moh_linelisting_persons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moh_linelisting',
        ),
    ]
