# Generated by Django 2.0 on 2019-08-13 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0029_delete_moh_linelisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='phone_number',
            field=models.CharField(default='0700000000', max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,12}$')]),
        ),
    ]
