# Generated by Django 2.0 on 2019-08-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0030_persons_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='access_level',
            field=models.CharField(default='National', max_length=10),
        ),
    ]
