# Generated by Django 2.0 on 2019-08-14 11:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veoc', '0031_persons_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='standard_case_definitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=50)),
                ('incubation_period', models.CharField(max_length=50)),
                ('suspected_standard_case_def', models.CharField(max_length=200)),
                ('confirmed_standard_case_def', models.CharField(max_length=200)),
                ('signs_and_symptoms', models.CharField(max_length=200)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_case_updated_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_case_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-code'],
            },
        ),
    ]
