# Generated by Django 2.0 on 2019-08-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0032_standard_case_definitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard_case_definitions',
            name='confirmed_standard_case_def',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='standard_case_definitions',
            name='signs_and_symptoms',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='standard_case_definitions',
            name='suspected_standard_case_def',
            field=models.CharField(max_length=1000),
        ),
    ]
