# Generated by Django 2.0 on 2019-08-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0035_auto_20190819_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='idsr_weekly_national_report',
            name='idsr_incident_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='veoc.idsr_reported_incidents'),
        ),
        migrations.AlterField(
            model_name='idsr_weekly_national_report',
            name='idsr_disease_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='veoc.idsr_diseases'),
        ),
    ]
