# Generated by Django 2.0 on 2019-08-21 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0036_auto_20190819_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='county',
            field=models.ForeignKey(default='2620', on_delete=django.db.models.deletion.CASCADE, related_name='persons_county', to='veoc.organizational_units'),
        ),
        migrations.AddField(
            model_name='persons',
            name='sub_county',
            field=models.ForeignKey(blank=True, default='2620', on_delete=django.db.models.deletion.CASCADE, related_name='persons_subcounty', to='veoc.organizational_units'),
        ),
    ]
