# Generated by Django 2.0 on 2019-08-21 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0037_auto_20190821_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='idsr_weekly_facility_report',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='idsr_weekly_national_report',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
