# Generated by Django 2.0 on 2019-08-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0038_auto_20190821_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idsr_weekly_facility_report',
            name='data_value',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='idsr_weekly_national_report',
            name='data_value',
            field=models.FloatField(max_length=50),
        ),
    ]
