# Generated by Django 2.0 on 2019-09-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0040_v_dhis_national_data_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='police_post',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='police_post',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='referral_labs',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='referral_labs',
            name='longitude',
        ),
        migrations.AddField(
            model_name='police_post',
            name='ward',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_ward', to='veoc.organizational_units'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral_labs',
            name='ward',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='veoc.organizational_units'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_county', to='veoc.organizational_units'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subcounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_subcounty', to='veoc.organizational_units'),
        ),
        migrations.AlterField(
            model_name='police_post',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_county', to='veoc.organizational_units'),
        ),
        migrations.AlterField(
            model_name='police_post',
            name='subcounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_subcounty', to='veoc.organizational_units'),
        ),
        migrations.AlterField(
            model_name='referral_labs',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refferal_county', to='veoc.organizational_units'),
        ),
        migrations.AlterField(
            model_name='referral_labs',
            name='subcounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refferal_subcounty', to='veoc.organizational_units'),
        ),
    ]
