# Generated by Django 2.0 on 2019-09-05 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0041_auto_20190905_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_contact',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_staff_designation', to='veoc.designation'),
        ),
    ]
