# Generated by Django 2.0 on 2019-09-06 08:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veoc', '0042_auto_20190905_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='watcher_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField(default=0)),
                ('from_date', models.CharField(default='', max_length=500)),
                ('to_date', models.CharField(default='', max_length=500)),
                ('deleted', models.CharField(default='N', max_length=20)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_updated_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_created_by', to=settings.AUTH_USER_MODEL)),
                ('watcher_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watcher_details', to='veoc.staff_contact')),
            ],
        ),
    ]
