# Generated by Django 2.0 on 2019-09-07 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0043_watcher_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_type',
            new_name='type_of_contact',
        ),
    ]
