# Generated by Django 2.0 on 2020-01-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0047_auto_20190912_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='eoc_events_calendar',
            name='time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
