# Generated by Django 2.0 on 2020-01-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0048_eoc_events_calendar_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_contact',
            name='team_lead',
            field=models.BooleanField(default=False),
        ),
    ]
