# Generated by Django 2.0 on 2020-02-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0050_v_dhis_national_report_data_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhis_disease_type',
            name='infectious_disease',
            field=models.BooleanField(default=False),
        ),
    ]
