# Generated by Django 2.0 on 2020-02-25 12:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veoc', '0051_dhis_disease_type_infectious_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='infectious_disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateTimeField(default=datetime.datetime.now)),
                ('remarks', models.TextField(max_length=500)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infectious_disease_updated_by', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.data_source')),
                ('disease_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infectious_disease_types', to='veoc.dhis_disease_type')),
                ('incident_status', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='veoc.incident_status')),
                ('reporting_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.reporting_region')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infectious_disease_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
