# Generated by Django 2.0 on 2020-02-25 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0052_infectious_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard_case_definitions',
            name='condition',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_case_disease_types', to='veoc.dhis_disease_type'),
        ),
        migrations.AlterField(
            model_name='standard_case_definitions',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_case_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='standard_case_definitions',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='std_case_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
