# Generated by Django 2.0 on 2020-03-13 10:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0053_auto_20200225_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='quarantine_contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,12}$')])),
                ('email_address', models.EmailField(blank=True, max_length=20)),
                ('origin_country', models.CharField(max_length=50)),
                ('place_of_diagnosis', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('date_of_contact', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('county', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_county', to='veoc.organizational_units')),
                ('subcounty', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_subcounty', to='veoc.organizational_units')),
            ],
        ),
        migrations.CreateModel(
            name='quarantine_follow_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_quarantine', models.BooleanField(default=False)),
                ('test_day', models.CharField(max_length=50)),
                ('thermal_gun', models.BooleanField(default=False)),
                ('body_temperature', models.IntegerField()),
                ('symptoms', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('patient_contacts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='followup_contact', to='veoc.quarantine_contacts')),
            ],
        ),
    ]
