# Generated by Django 2.0 on 2020-03-13 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veoc', '0054_quarantine_contacts_quarantine_follow_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantine_contacts',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_updated_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarantine_contacts',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
