# Generated by Django 2.0 on 2020-03-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0055_auto_20200313_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarantine_follow_up',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='quarantine_follow_up',
            name='cough',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarantine_follow_up',
            name='difficulty_breathing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarantine_follow_up',
            name='fever',
            field=models.BooleanField(default=False),
        ),
    ]
