# Generated by Django 2.0 on 2020-03-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0056_auto_20200314_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantine_follow_up',
            name='follow_up_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
