# Generated by Django 2.0 on 2020-03-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0061_quarantine_contacts_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantine_follow_up',
            name='body_temperature',
            field=models.FloatField(),
        ),
    ]
