# Generated by Django 2.0 on 2020-03-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0062_auto_20200317_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantine_follow_up',
            name='comment',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
