# Generated by Django 2.0 on 2020-03-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0063_quarantine_follow_up_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantine_contacts',
            name='data_source',
            field=models.CharField(default='web', max_length=50),
            preserve_default=False,
        ),
    ]
