# Generated by Django 2.0 on 2020-03-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0064_quarantine_contacts_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantine_follow_up',
            name='sms_status',
            field=models.BooleanField(default=False),
        ),
    ]
