# Generated by Django 2.0 on 2020-03-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0065_quarantine_follow_up_sms_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantine_follow_up',
            name='sms_status',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
