# Generated by Django 2.0 on 2020-03-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0066_auto_20200318_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarantine_contacts',
            old_name='data_source',
            new_name='source',
        ),
    ]
