# Generated by Django 2.0 on 2020-03-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0067_auto_20200319_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantine_follow_up',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quarantine_follow_up',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
