# Generated by Django 2.0 on 2020-03-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0070_auto_20200330_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
    ]
