# Generated by Django 2.0 on 2020-03-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0071_auto_20200330_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='nationality',
            field=models.CharField(default='KENYA', max_length=50),
        ),
    ]
