# Generated by Django 2.0 on 2020-04-01 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0072_auto_20200330_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 8, 7, 52, 142051)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='origin_country',
            field=models.CharField(default='KENYA', max_length=50),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 8, 7, 52, 142051)),
        ),
    ]
