# Generated by Django 2.0 on 2020-04-05 06:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0074_auto_20200405_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 9, 4, 34, 482279)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='place_of_diagnosis',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quarantine_site', to='veoc.quarantine_sites'),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 9, 4, 34, 482279)),
        ),
    ]
