# Generated by Django 2.0 on 2020-04-05 08:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0075_auto_20200405_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantine_contacts',
            name='quarantine_site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quarantine_site', to='veoc.quarantine_sites'),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 11, 46, 25, 972683)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='place_of_diagnosis',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 11, 46, 25, 972683)),
        ),
    ]
