# Generated by Django 2.0 on 2020-04-05 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0076_auto_20200405_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantine_contacts',
            name='contact_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quarantine_contacts',
            name='contact_uuid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quarantine_contacts',
            name='physical_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 15, 4, 5, 311496)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 15, 4, 5, 311496)),
        ),
    ]
