# Generated by Django 2.0 on 2020-04-13 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0077_auto_20200405_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantine_sites',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 17, 58, 18, 223106)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 17, 58, 18, 224103)),
        ),
    ]
