# Generated by Django 3.0.6 on 2020-06-05 18:20

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veoc', '0078_auto_20200413_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='border_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('border_name', models.CharField(max_length=50)),
                ('border_location', models.CharField(max_length=50)),
                ('team_lead_names', models.CharField(max_length=500)),
                ('team_lead_phone', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,15}$')])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='border_points_updated_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='border_points_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='covid_results_classifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='covid_sample_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='testing_labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='translation_languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=20)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_updated_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quarantine_contacts',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quarantine_sites',
            name='county',
            field=models.ForeignKey(blank=True, default=16256, on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_site_county', to='veoc.organizational_units'),
        ),
        migrations.AddField(
            model_name='quarantine_sites',
            name='subcounty',
            field=models.ForeignKey(blank=True, default=12324, on_delete=django.db.models.deletion.CASCADE, related_name='quarantine_site_subcounty', to='veoc.organizational_units'),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 21, 20, 11, 957716)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='nok_phone_num',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='phone_number',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 21, 20, 11, 957716)),
        ),
        migrations.AlterField(
            model_name='quarantine_follow_up',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 5, 21, 20, 11, 957716)),
        ),
        migrations.CreateModel(
            name='weighbridge_sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighbridge_name', models.CharField(max_length=50)),
                ('weighbridge_location', models.CharField(max_length=50)),
                ('team_lead_names', models.CharField(max_length=500)),
                ('team_lead_phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,15}$')])),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='weighbridge_sites_updated_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='weighbridge_sites_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='truck_quarantine_lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_sample_uuid', models.CharField(blank=True, max_length=50)),
                ('covid_test_done', models.BooleanField(default=False)),
                ('specimen_taken', models.BooleanField(default=False)),
                ('reason_specimen_not_taken', models.CharField(blank=True, max_length=255)),
                ('date_specimen_collected', models.DateTimeField(default=datetime.datetime(2020, 6, 5, 21, 20, 11, 960708))),
                ('other_specimen_type', models.CharField(blank=True, max_length=50)),
                ('viral_respiratory_illness', models.BooleanField(default=False)),
                ('respiratory_illness_results', models.CharField(blank=True, max_length=50)),
                ('date_specimen_taken_lab', models.DateTimeField(default=datetime.datetime(2020, 6, 5, 21, 20, 11, 960708))),
                ('date_lab_confirmation', models.DateTimeField(default=datetime.datetime(2020, 6, 5, 21, 20, 11, 960708))),
                ('processed', models.IntegerField(blank=True, default=0)),
                ('received', models.IntegerField(null=True)),
                ('lab_sample_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 6, 5, 21, 20, 11, 960708))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 6, 5, 21, 20, 11, 960708))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='truck_lab_updated_by', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_name', to='veoc.testing_labs')),
                ('lab_results', models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_results', to='veoc.covid_results_classifications')),
                ('patient_contacts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='truck_lab_contact', to='veoc.quarantine_contacts')),
                ('specimen_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_specimen_type', to='veoc.covid_sample_types')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='truck_lab_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='truck_quarantine_contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=50)),
                ('village', models.CharField(blank=True, max_length=50)),
                ('vehicle_registration', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('company_phone', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,15}$')])),
                ('company_physical_address', models.CharField(blank=True, max_length=50)),
                ('company_street', models.CharField(blank=True, max_length=50)),
                ('company_building', models.CharField(blank=True, max_length=50)),
                ('cough', models.BooleanField(default=True)),
                ('breathing_difficulty', models.BooleanField(default=True)),
                ('fever', models.BooleanField(default=True)),
                ('temperature', models.FloatField(blank=True, default='0.0', max_length=20)),
                ('sample_taken', models.BooleanField(default=True)),
                ('action_taken', models.CharField(blank=True, max_length=100)),
                ('hotel', models.CharField(blank=True, max_length=50)),
                ('hotel_phone', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,15}$')])),
                ('hotel_town', models.CharField(blank=True, max_length=50)),
                ('date_check_in', models.DateField(default=datetime.date.today)),
                ('date_check_out', models.DateField(default=datetime.date.today)),
                ('border_point', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='border_contact_facility', to='veoc.border_points')),
                ('patient_contacts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='truck_quarantine_contact', to='veoc.quarantine_contacts')),
                ('weighbridge_facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='weighbridge_contact_facility', to='veoc.weighbridge_sites')),
            ],
        ),
        migrations.CreateModel(
            name='translation_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.CharField(max_length=200)),
                ('message_description', models.CharField(max_length=50)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massage_updated_by', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veoc.translation_languages')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massage_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quarantine_contacts',
            name='communication_language',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='quarantine_language', to='veoc.translation_languages'),
        ),
    ]
