# Generated by Django 3.0.6 on 2020-06-16 07:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veoc', '0082_auto_20200611_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 10, 7, 32, 876732)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 10, 7, 32, 876732)),
        ),
        migrations.AlterField(
            model_name='quarantine_follow_up',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 10, 7, 32, 877729)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 10, 7, 32, 879721)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_lab_confirmation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 10, 7, 32, 879721)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_specimen_collected',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 10, 7, 32, 879721)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_specimen_taken_lab',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 10, 7, 32, 879721)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 10, 7, 32, 879721)),
        ),
        migrations.CreateModel(
            name='home_based_care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 6, 16, 10, 7, 32, 880718))),
                ('health_care_worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='health_care_worker_contact', to=settings.AUTH_USER_MODEL)),
                ('patient_contacts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_care_contact', to='veoc.quarantine_contacts')),
            ],
        ),
        migrations.CreateModel(
            name='discharged_quarantine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 6, 16, 10, 7, 32, 880718))),
                ('health_care_worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='health_care_worker_discharged_quarantine', to=settings.AUTH_USER_MODEL)),
                ('patient_contacts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='discharged_quarantine_contact', to='veoc.quarantine_contacts')),
            ],
        ),
    ]
