# Generated by Django 3.0.6 on 2020-06-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0085_auto_20200620_2019'),
        ('veoc', '0085_auto_20200616_1216'),
    ]

    operations = [
    ]
