# Generated by Django 3.0.6 on 2020-06-25 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0086_merge_20200625_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='moh_line_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=20)),
                ('facility_name', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
                ('patient_names', models.CharField(max_length=200)),
                ('patient_status', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=50)),
                ('disease_condition', models.CharField(max_length=50)),
                ('date_seen_at_facility', models.DateField(max_length=20)),
                ('date_onset_disease', models.CharField(max_length=20)),
                ('no_doses_of_vaccine', models.IntegerField(max_length=20)),
                ('lab_test', models.CharField(max_length=50)),
                ('outcome', models.CharField(max_length=50)),
                ('epi_week', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='discharged_quarantine',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 23, 54, 51, 108662)),
        ),
        migrations.AlterField(
            model_name='home_based_care',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 23, 54, 51, 108662)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 23, 54, 51, 103675)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 23, 54, 51, 103675)),
        ),
        migrations.AlterField(
            model_name='quarantine_follow_up',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 23, 54, 51, 104672)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 23, 54, 51, 107665)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_lab_confirmation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 23, 54, 51, 107665)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_specimen_collected',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 23, 54, 51, 107665)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_specimen_taken_lab',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 23, 54, 51, 107665)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 25, 23, 54, 51, 107665)),
        ),
    ]
