# Generated by Django 3.0.6 on 2020-06-27 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0087_auto_20200625_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarantine_contacts',
            name='active_follow_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discharged_quarantine',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 14, 22, 22, 700138)),
        ),
        migrations.AlterField(
            model_name='home_based_care',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 14, 22, 22, 699138)),
        ),
        migrations.AlterField(
            model_name='moh_line_listing',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moh_line_listing',
            name='no_doses_of_vaccine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 14, 22, 22, 694140)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 14, 22, 22, 694140)),
        ),
        migrations.AlterField(
            model_name='quarantine_follow_up',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 14, 22, 22, 695265)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 14, 22, 22, 699138)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_lab_confirmation',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 14, 22, 22, 699138)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_specimen_collected',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 14, 22, 22, 698141)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_specimen_taken_lab',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 14, 22, 22, 698141)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 14, 22, 22, 699138)),
        ),
    ]
