# Generated by Django 3.0.6 on 2020-07-01 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0089_auto_20200629_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck_quarantine_lab',
            name='covid_test_done',
        ),
        migrations.RemoveField(
            model_name='truck_quarantine_lab',
            name='date_specimen_taken_lab',
        ),
        migrations.RemoveField(
            model_name='truck_quarantine_lab',
            name='other_specimen_type',
        ),
        migrations.RemoveField(
            model_name='truck_quarantine_lab',
            name='reason_specimen_not_taken',
        ),
        migrations.RemoveField(
            model_name='truck_quarantine_lab',
            name='respiratory_illness_results',
        ),
        migrations.RemoveField(
            model_name='truck_quarantine_lab',
            name='specimen_taken',
        ),
        migrations.RemoveField(
            model_name='truck_quarantine_lab',
            name='viral_respiratory_illness',
        ),
        migrations.AddField(
            model_name='truck_quarantine_lab',
            name='case_identification_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='truck_quarantine_lab',
            name='confirmed_case_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='truck_quarantine_lab',
            name='contact_with_case',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='truck_quarantine_lab',
            name='have_symptoms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='truck_quarantine_lab',
            name='onset_of_symptoms',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 17, 16, 22, 792287)),
        ),
        migrations.AddField(
            model_name='truck_quarantine_lab',
            name='sample_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='truck_quarantine_lab',
            name='symptoms_shown',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='truck_quarantine_lab',
            name='travel_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='truck_quarantine_lab',
            name='type_of_case',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='discharged_quarantine',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 17, 16, 22, 793284)),
        ),
        migrations.AlterField(
            model_name='home_based_care',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 17, 16, 22, 793284)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 17, 16, 22, 788298)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 17, 16, 22, 788298)),
        ),
        migrations.AlterField(
            model_name='quarantine_follow_up',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 17, 16, 22, 789295)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 17, 16, 22, 792287)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_lab_confirmation',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 17, 16, 22, 792287)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_specimen_collected',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 17, 16, 22, 792287)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='test_sample_uuid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 17, 16, 22, 792287)),
        ),
        migrations.CreateModel(
            name='quarantine_revisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_revisit', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 7, 1, 17, 16, 22, 789295))),
                ('patient_contacts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='revisit_contact', to='veoc.quarantine_contacts')),
                ('quarantine_site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quarantine_revisit_site', to='veoc.quarantine_sites')),
            ],
        ),
    ]
