# Generated by Django 3.0.6 on 2020-07-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0093_auto_20200705_0921'),
        ('veoc', '0093_auto_20200706_1233'),
    ]

    operations = [
    ]
