# Generated by Django 3.0.6 on 2020-07-18 09:15

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0098_auto_20200715_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharged_quarantine',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 850680)),
        ),
        migrations.AlterField(
            model_name='home_based_care',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 850680)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 845695)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 845695)),
        ),
        migrations.AlterField(
            model_name='quarantine_follow_up',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 846698)),
        ),
        migrations.AlterField(
            model_name='quarantine_revisit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 848689)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 849686)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_lab_confirmation',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 849686)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_specimen_collected',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 849686)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='onset_of_symptoms',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 849686)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 849686)),
        ),
        migrations.CreateModel(
            name='covid_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10,15}$')])),
                ('lab', models.CharField(blank=True, max_length=200)),
                ('date_tested', models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 848689))),
                ('result', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 848689))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 848689))),
                ('api_processed', models.IntegerField(default=0)),
                ('api_access_date', models.DateTimeField(default=datetime.datetime(2020, 7, 18, 12, 15, 28, 848689))),
                ('source', models.CharField(max_length=200)),
                ('patient_contacts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='results_contact', to='veoc.quarantine_contacts')),
            ],
        ),
    ]
