# Generated by Django 3.0.6 on 2020-07-28 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0100_auto_20200727_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='v_follow_up',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('patient_contacts_id', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('passport_number', models.CharField(max_length=200)),
                ('reporting_date', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('subcounty', models.CharField(max_length=200)),
                ('self_quarantine', models.BooleanField(default=True)),
                ('follow_up_day', models.CharField(max_length=200)),
                ('thermal_gun', models.BooleanField(default=True)),
                ('body_temperature', models.BooleanField(default=True)),
                ('cough', models.BooleanField(default=True)),
                ('difficulty_breathing', models.BooleanField(default=True)),
                ('fever', models.BooleanField(default=True)),
                ('comment', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'v_follow_up',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='v_lab_results',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('patient_contacts_id', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('testing_lab', models.CharField(max_length=200)),
                ('date_tested', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('system_registration_date', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('origin_country', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('sub_county', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('border_name', models.CharField(max_length=200)),
                ('date_received', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'v_lab_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='v_quarantine_contacts',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contact_id', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('passport_number', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('origin_country', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('subcounty', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('quarantine_site', models.CharField(max_length=200)),
                ('sms_communication_language', models.CharField(max_length=200)),
                ('date_of_contact', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'v_quarantine_contacts',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 331147)),
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='temperature',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 331147)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='api_access_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 313332)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 313332)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='date_tested',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 313332)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 313332)),
        ),
        migrations.AlterField(
            model_name='discharged_quarantine',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 315187)),
        ),
        migrations.AlterField(
            model_name='home_based_care',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 315187)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 310192)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 310192)),
        ),
        migrations.AlterField(
            model_name='quarantine_follow_up',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 311154)),
        ),
        migrations.AlterField(
            model_name='quarantine_revisit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 313332)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 314183)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_lab_confirmation',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 314183)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_specimen_collected',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 314183)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='onset_of_symptoms',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 314183)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 6, 5, 24, 314183)),
        ),
    ]
