# Generated by Django 2.0 on 2020-07-31 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0103_auto_20200728_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='quarantine_list_view',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('_id', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('passport_number', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('origin_country', models.CharField(max_length=200)),
                ('border_name', models.CharField(max_length=200)),
                ('date_of_contact', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'quarantine_list_view',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 639158)),
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 639158)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='api_access_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 624198)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 624198)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 624198)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 624198)),
        ),
        migrations.AlterField(
            model_name='discharged_quarantine',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 627190)),
        ),
        migrations.AlterField(
            model_name='home_based_care',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 627190)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 618309)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 618309)),
        ),
        migrations.AlterField(
            model_name='quarantine_follow_up',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 619349)),
        ),
        migrations.AlterField(
            model_name='quarantine_revisit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 623201)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 626193)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_lab_confirmation',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 626193)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_specimen_collected',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 626193)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='onset_of_symptoms',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 626193)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 14, 5, 18, 626193)),
        ),
    ]
