# Generated by Django 2.0 on 2020-08-01 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veoc', '0107_auto_20200801_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline_quarantine',
            name='airline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='arrival_airport_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 820483)),
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='destination_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='estate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='flight_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='measured_temperature',
            field=models.FloatField(blank=True, default='0.0', max_length=53),
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='residence',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='seat_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='travel_history',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='airline_quarantine',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 820483)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='api_access_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 809546)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 809546)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 809546)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 809546)),
        ),
        migrations.AlterField(
            model_name='discharged_quarantine',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 811513)),
        ),
        migrations.AlterField(
            model_name='home_based_care',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 811513)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 805489)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 805489)),
        ),
        migrations.AlterField(
            model_name='quarantine_follow_up',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 806666)),
        ),
        migrations.AlterField(
            model_name='quarantine_revisit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 808515)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 810509)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_lab_confirmation',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 810509)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_specimen_collected',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 810509)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='onset_of_symptoms',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 810509)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 51, 38, 810509)),
        ),
    ]
