# Generated by Django 2.0 on 2020-08-01 06:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veoc', '0109_auto_20200801_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='airline_quarantine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(blank=True, max_length=255)),
                ('flight_number', models.CharField(blank=True, max_length=32)),
                ('seat_number', models.CharField(blank=True, max_length=32)),
                ('destination_city', models.CharField(blank=True, max_length=255)),
                ('travel_history', models.CharField(blank=True, max_length=255)),
                ('cough', models.BooleanField(default=True)),
                ('breathing_difficulty', models.BooleanField(default=True)),
                ('fever', models.BooleanField(default=True)),
                ('chills', models.BooleanField(default=True)),
                ('temperature', models.BooleanField(default=True)),
                ('residence', models.CharField(blank=True, max_length=255)),
                ('postal_address', models.CharField(blank=True, max_length=255)),
                ('estate', models.CharField(blank=True, max_length=255)),
                ('measured_temperature', models.FloatField(blank=True, default='0.0', max_length=53)),
                ('arrival_airport_code', models.CharField(blank=True, max_length=255)),
                ('released', models.BooleanField(default=True)),
                ('risk_assessment_referal', models.BooleanField(default=True)),
                ('designated_hospital_refferal', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 940386))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 940386))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='airline_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='api_access_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 920393)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 920393)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 920393)),
        ),
        migrations.AlterField(
            model_name='covid_results',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 920393)),
        ),
        migrations.AlterField(
            model_name='discharged_quarantine',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 923445)),
        ),
        migrations.AlterField(
            model_name='home_based_care',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 922421)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 917439)),
        ),
        migrations.AlterField(
            model_name='quarantine_contacts',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 917439)),
        ),
        migrations.AlterField(
            model_name='quarantine_follow_up',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 917439)),
        ),
        migrations.AlterField(
            model_name='quarantine_revisit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 920393)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 922421)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_lab_confirmation',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 922421)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='date_specimen_collected',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 921424)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='onset_of_symptoms',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 921424)),
        ),
        migrations.AlterField(
            model_name='truck_quarantine_lab',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 9, 57, 16, 922421)),
        ),
        migrations.AddField(
            model_name='airline_quarantine',
            name='patient_contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='airline_contact', to='veoc.quarantine_contacts'),
        ),
        migrations.AddField(
            model_name='airline_quarantine',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='airline_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
